project_id = "aazshokdhlodzaafrifh"

[functions.test-whatsapp]
verify_jwt = false

[functions.get-due-items]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.get-message-template]
verify_jwt = false

[functions.prepare-message]
verify_jwt = false

[functions.search-items]
verify_jwt = false

[functions.get-item-details]
verify_jwt = false

[functions.log-conversation]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false
